---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == 'Debian'

- name: Install tree and git on Debian
  apt:
    name:
      - tree
      - git
    state: present
  when: ansible_os_family == 'Debian'

- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install tree and git on RedHat
  yum:
    name:
      - tree
      - git
    state: present
  when: ansible_os_family == 'RedHat'
